[package]
name = "slices"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "diagram"
path = "src/diagram-what-is-different-about-this-book.rs"

[[bin]]
name = "exercise"
path = "src/exercise-ch04-04-slices-question-2.rs"

[[bin]]
name = "solution"
path = "src/solution-ch04-04-slices-question-2.rs"

[[bin]]
name = "first-word"
path = "src/first-word-ch04-04.rs"